name = "apk-builder"
main = "src/index.js"
compatibility_date = "2023-10-30"

[vars]
GITHUB_USER = "luizotavio854h-alt"
GITHUB_REPO = "apk-builder"

[[kv_namespaces]]
binding = "TICKETS"
id = "3ed7420df8334d56a8f079c4d6592726"

[triggers]
crons = ["0 * * * *"]
