name = "samp-compiler-bot"
main = "src/index.js"
compatibility_date = "2023-10-30"

[vars]
GITHUB_USER = "48348484488"
GITHUB_REPO = "SAMP-Discord-Bot-Repo"

[[kv_namespaces]]
binding = "TICKETS"
id = "038fa2ca0b7e4b5c8189df0b4ba6a4fc"

[triggers]
crons = ["0 * * * *"]
